### ISSUE TITLE
shake errors from using nix installed stack?

### ISSUE THREAD

**Issue by ghost** [adept/full-fledged-hledger#1]
Hi, 
Thanks for building this system and publishing it.
I am trying running `export.sh` for generating reports, but see the following error:
```
Error when running Shake build system:
* 2018-all.journal
* 2018-closing.journal
hledger: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
I have installed stack using nix and my `~/.stack/config.yaml` as the following:
```yaml
ghc-build: nopie
nix:
  enable: true
```
Found a similar error here, but I am no haskeller so not sure  what to make of it:
https://github.com/tweag/HaskellR/issues/286

**Comment by adept** [comment]
Looks like it tried to run `hledger`, but it was not in your $PATH. Did you manage to get this resolved?

**Comment by ghost** [comment]
ah, interesting. haven't gotten to retrying but will try to this week.

**Comment by ghost** [comment]
Thanks for the advice. I was able to get it running by specifying the full path's to where hledger and other invoked binaries are. Since nixOS has its own prefixed installs for these binaries I can't  call `/usr/bin/awk`  or things like that.
