### ISSUE TITLE
Wish: being able to pass-through an hledger argument (such as account query) to export.hs

### ISSUE THREAD

**Issue by lestephane** [adept/full-fledged-hledger#11]
A way to select a specific account hierarchy is something else that came to mind since filing #10, as my personal and business books are in the same import filesystem hierarchy. The usual way for me to do this is to add `^Business` or `^Personal` to my hledger commands. I'd need to do this through a command-line argument pass-through as well if I don't want to modify the git cloned `export.hs` of full-fledged-hledger.

My account hierarchy looks like
- `Business-<Country Code>:(Expenses|Income|...)`
- `Personal:(Expenses|Income|...)`

Maybe a generic hledger option pass-through command-line argument is all that's needed, and would be useful not just for this use-case. For example, one could pass another `-f aliases.journal` containing account aliases to adjust a chart of accounts to a specific situation / jurisdiction / tax system / accountant. 

Now, I did look at the diff for #10 to see how parsing command-line arguments works and maybe submit a PR, but I'm not familiar with haskell and the syntax is kind of intimidating to an imperative-first programmer such as myself. I'm learning Scala, but I'm not there yet. Hopefully this is an easy change for you.

**Comment by adept** [comment]
How would an ability to pass through something like "^Business" would help you, though?
My understanding is that if you generate a set of reports for "^Business", next run with "^Personal" (perhaps with --rebuild) would overwrite all the report files with personal content. 

Perhaps you would rather have two separate set of report files (like 2014-personal-balance-sheet.txt and 2014-business-balance-sheet.txt and so on)?

The easiest way to do that would be to add more reports to "reports" function:
```
personal_balance_sheet     y = y++"-personal-balance-sheet.txt"
business_balance_sheet     y = y++"-business-balance-sheet.txt

reports first current =
  concat [ [ transactions         (show y) | y <- all_years ]
        , [ personal_balance_sheet        (show y) | y <- all_years ]
        , [ business_balance_sheet        (show y) | y <- all_years ]
         ...
         ]
  where
    all_years=[first..current]
```

and then you supply command line arguments in the rules to build each report:
```
  (personal_balance_sheet "//*") %> hledger_process_year base year_inputs ["balancesheet", "^Personal"]
  (business_balance_sheet "//*") %> hledger_process_year base year_inputs ["balancesheet", "^Business"]
```

How does this sound?

**Comment by lestephane** [comment]
I'm worried that I'm going to deviate from the original `export.hs`, and the syntax is intimidating.

I'd prefer to pass an account query, and export output directory (example: `/some/export/path`), or export path prefix (example: `/some/export/path/personal-`) directly as `export.hs` command-line parameter.

Failing that, I'll go the suggested route.

**Comment by adept** [comment]
I don't think it makes sense to pass accounts query to all invocations of hledger in `export.hs` -- there are some invocations where it would not make much sense.

However, I pushed some changes into master that would allow one to specify the name of the hledger binary to use and account query used to generate opening/closing balances. I think that you can make minimal shell wrapper around hledger to achieve what you want, something like this:
```
#!/bin/bash
if [ "$2" = "balance" ] ; then 
  hledger "$@" "^Business"
else
  hledger "$@"
fi
```

I think this is generic enough and at the same time should cover your use case. What do you think?

**Comment by adept** [comment]
It has been 19 days. I am going to close this issue now, feel free to reopen if needed
