### ISSUE TITLE
Getting started - broken URLs

### ISSUE THREAD

**Issue by sebastianschauenburg** [adept/full-fledged-hledger#12]
The "Getting started" wiki page contains several links to to https://github.com/simonmichael/hledger/wiki/* (specifically the "hledger basics tutorial" and "hledger accounting concepts"). But that wiki seems to have disappeared. Since I don't know the exact content, I wonder what to replace it with. Would "https://hledger.org/accounting.html" suffice? (it also contains dead links to basics by the way)

**Comment by adept** [comment]
Thank you! I fixed both links.

**Comment by simonmichael** [comment]
And I fixed mine, thanks.
