### ISSUE TITLE
Safe to add export/.shake/ to .gitignore?

### ISSUE THREAD

**Issue by josephmturner** [adept/full-fledged-hledger#15]
`export/.shake/.shake.database` updates every time I run the export script. Is it safe to add it to .gitignore?

**Comment by adept** [comment]
I think current .gitignore already handles this? Last two lines?

```
$ git log 09-remortgage/export/.shake/.shake.database
(no output)
```

**Comment by josephmturner** [comment]
You're right. Thank you - I had forgotten to copy over the .gitignore from the full-fledged-hledger when I made my own.
