### ISSUE TITLE
Thank You So Much - This Repo Is Great

### ISSUE THREAD

**Issue by markus1189** [adept/full-fledged-hledger#24]
Hey,

this is not a real issue, so feel free to close it immediately after reading, I just wanted to say thanks. 

I am experienced in haskell and love shake, so I might be biased, but this workflow together with the step wise tutorial was a real dream come true for me. 

So many of my open questions about "how do I do this in hledger?" have been answered, I wanted to explicitly tell you of how much help this was for me.

Best,
Markus

**Comment by adept** [comment]
Thank you very much! Comments like yours give me the inspiration to come back and add more :) Much appreciated!
