### ISSUE TITLE
export.sh not running in2csv or csv2journal

### ISSUE THREAD

**Issue by MichaelVessia** [adept/full-fledged-hledger#6]
Hello,

I have enjoyed reading through the wiki and tutorial chapters and would like to use some of these techniques in my own hledger setup.  I am starting by copying and adapting some key files from chapter 2.  My issue is that `export.sh` (and thus by extension `export.hs`) do not seem to be running the `in2csv` and `csv2journal` scripts.  I have even copied the `import/` directory from the 02 chapter as well as the export scripts and it won't recreate the `lloyds` csv or journal files either.  It generates the other reports (cashflow etc)

If I run `export.sh` inside of the full-fledger-hledger repo i cloned, it does work, so I am looking for ways to figure out why in my repo it does not run the appropriate scripts.

Thanks for any help you can provide, and let me know if additional information is helpful.

**Comment by MichaelVessia** [comment]
It's also worth mentioning that `in2csv` and `csv2journal` work fine if manually invoked, but the export.hs pipeline seems to fail to invoke those scripts in my repo

**Comment by adept** [comment]
1. You might gain some insights by running `export --rebuild --trace`
2. Did you take your `export/export.hs` from chapter 01 or chapter 02? They are different (you can see changes in  `diffs/01-to-02.diff`), in particular, import directories are listed around line 82, near "-- Enumerate directories with auto-generated cleaned csv files" - could this be the issue?

**Comment by MichaelVessia** [comment]
Hi @adept ,

I have run `export --rebuild --trace` but it does not provide information, it just tells me that the txt file reports have been generated.

I have taken `export.hs` from chapter 02, and modified it accordingly to match my files and years:

```
mike@michaelv:~/finances$ tree .
.
├── 2019.journal
├── all.journal
├── export
│   ├── 2019-all.journal
│   ├── 2019-balance-sheet.txt
│   ├── 2019-cash-flow.txt
│   ├── 2019-income-expenses.txt
│   └── export.hs
├── export.sh
├── import
│   └── aggregate
│       ├── aggregate.rules
│       ├── csv
│       ├── csv2journal
│       ├── in
│       │   └── 2019-01-01_thru_2019-07-29_transactions.csv
│       ├── in2csv
│       └── journal
```


And the excerpt from `export.hs`:

```
  -- Enumerate directories with auto-generated cleaned csv files
  [ "//import/aggregate/csv/*.csv" ] |%> in2csv

  -- Enumerate directories with auto-generated journals
  [ "//import/aggregate/journal/*.journal" ] |%> csv2journal
```

I have also tried substituting my `aggregate` directory with `lloyds` copied from the 02 chapter using the `export.hs` from the same chapter to no avail.

**Comment by adept** [comment]
Question: do you have '!include ./import/aggregate/journal/2019-01-01_thru_2019-07-29_transactions.journal' in your toplevel 2019.journal?

If you don't, then from build system perspective there is no need to build 2019-01-01_thru_2019-07-29_transactions.journal (and run conversion scripts)

**Comment by MichaelVessia** [comment]
@adept I do not have it there.  When i return to my computer I will try that.  That makes sense - thank you very much.  I will close this issue once I have confirmed it works!

**Comment by adept** [comment]
Yes, this is most probably it - export.sh (and export.hs) chase dependencies recursively starting from all.journal, and will only build/convert/refresh files that you actually use.

**Comment by MichaelVessia** [comment]
Adding the import to my top level journal solved my problem.  Thank you very much!
