### ISSUE TITLE
Include syntax

### ISSUE THREAD

**Issue by Simaex** [adept/full-fledged-hledger#9]
In the ["Getting full history of the account"](https://github.com/adept/full-fledged-hledger/wiki/Getting-full-history-of-the-account) tutorial it is suggested to use the next syntax of INCLUDE statement:
`!include filename`
But actually I have to use the next:
`include /filepath/filename`
Please let me know: this is some change that I missed or it is a typing mistake in tutorial?
I mean the exclamation symbol before command and obligatory usage of full file path.
I am using hledger 1.14.2 at the moment.

**Comment by adept** [comment]
Either syntax is acceptable, i just happen to use '!include'  (if I had to guess, probably because that syntax was historically first, and I never transitioned away from it)

**Comment by simonmichael** [comment]
Yes, `!include` was the original Ledger syntax. The `!` was dropped years ago, but it's still supported, in Ledger and hledger. Both of those examples work for me [in hledger 1.14](https://hledger.org/1.14/journal.html#including-other-files).

**Comment by Simaex** [comment]
Thank you for a prompt answer. Sorry I was not clear enough, the !include type of syntax just don't work for me, so I search for information why it may be so and found the other one that actually work. If you consider it worth correcting it I am ready to do the actual change.

**Comment by adept** [comment]
I've updated all 'include' statements in this repo to modern-day syntax
